spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./db/files/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret-key: "6ec035d91dc104db569a01a4d8c16fb13f125dc298992edfb8e66d3a837fe0c5"
      expiration-time: 3600000
